const articles =[
    {
        title:"Assinie",
        description:"Lorem",
        prix:"18000",
        image:"img/téléchargement.jpg",
        img1:"img/téléchargement.jpg",
        img2:"img/téléchargement.jpg",
        img3:"img/téléchargement.jpg",
        date:"15/07/2024",
        heure:"15h00",
        ville:"abidjan"
    },
    {
        title:"Zoo",
        description:"Lorem",
        prix:"18000",
        image:"img/téléchargement.jpg",
        img1:"img/téléchargement.jpg",
        img2:"img/téléchargement.jpg",
        img3:"img/téléchargement.jpg",
        date:"15/07/2024",
        heure:"15h00",
        ville:"abidjan"
    },
    {
        title:"Zoube",
        description:"Lorem",
        prix:"18000",
        image:"img/téléchargement.jpg",
        img1:"img/téléchargement.jpg",
        img2:"img/téléchargement.jpg",
        img3:"img/téléchargement.jpg",
        date:"15/07/2024",
        heure:"15h00",
        ville:"abidjan"
    },
];